### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [is541-sibsutis/crypt#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:

1. В [wiki](https://github.com/is541-sibsutis/crypt/wiki) проекта написана статья с ТЗ.
1. В [issues](https://github.com/is541-sibsutis/crypt/issues) созданы задачи.
1. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by 1e-to** [comment]
Т3 составили. Что надо исправить?

**Comment by evgeny-p** [comment]
1. Текст нечитабелен.
1. По описанию можно предположить, то приложение будет с графическим интерфейсом, но явно это нигде не отмечено. Уточните, средствами какой библиотеки будет реализован интерфейс.
1. Интерфейс предполагается делать сразу или он не входит в программу минимум?
1. Сохранять в файл можно, а читать из файла? Если приложение поддерживает только интерактивный режим работы — замучаетесь тестировать.
1. С наличием задачи на тестирование согласен, а пункт «устранение ошибок» указан преждевременно. В процессе тестирования на каждую ошибку заводится отдельная задача.
1. Аналогично с устранением неполадок и редизайном интерфейса. Еще нет ни неполадок, чтобы их устранять, ни дизайна, чтобы его менять.

**Comment by oriharaLOL** [comment]
Перепроверьте ТЗ, пожалуйста. Насчет библиотеки для интерфейса, мы разберемся с этим после того, как доделаем программу минимум.

**Comment by evgeny-p** [comment]
План работ оформить в виде задач (issues). Каждая задача назначается на исполнителя, выполняется в отдельной ветке. Мерж с опцией `--no-ff`, предварительно ветка ребейзится на последнее состояние мастера, см. практические занятия и https://gist.github.com/17twenty/6733076
